name: VaultStorage
version: '1.0.6'
main: net.democracycraft.vault.VaultStoragePlugin
api-version: '1.21'
authors: [ Alepando ]
depend: [ Bolt , WorldGuard, WorldEdit, Essentials ]

commands:
  vault:
    description: Vault storage tools
    usage: /vault [menu]
    permission: vaultstorage.user

permissions:
  vaultstorage.user:
    description: Allows using basic vault commands
    default: op
  vaultstorage.admin:
    description: Admin override for vault commands
    default: op
  vaultstorage.action.view:
    description: Allows viewing vaults in a virtual inventory
    default: true
  vaultstorage.action.edit:
    description: Allows editing vault contents in a virtual inventory
    default: op
  vaultstorage.action.copy:
    description: Allows copying items from a vault to the player inventory
    default: op
  vaultstorage.action.place:
    description: Allows placing back the original block and restoring its contents
    default: op
  vaultstorage.admin.override:
    description: Allows capturing/placing vault blocks even if not a region member or outside regions
    default: false
  vaultstorage.action.capture:
    description: Allows capturing a container into a vault (requires region ownership & container ownership unless override)
    default: op
